# Generated by Django 3.2.25 on 2024-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('event_datetime', models.DateTimeField()),
                ('description', models.TextField(max_length=4000)),
                ('duration', models.DurationField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
