# Generated by Django 3.2.25 on 2024-04-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_field',
        ),
    ]
