# Generated by Django 3.2.25 on 2024-04-25 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20240424_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(9, 46, 6, 796988), help_text='Enter time in the format of the 24 clock'),
        ),
    ]
