# Generated by Django 3.2.25 on 2024-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.CharField(default='This is a bio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
