# Generated by Django 3.2.25 on 2024-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(default='/media/noimage.png', upload_to=''),
        ),
    ]
