# Generated by Django 3.2.25 on 2024-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='by_age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_arrival',
        ),
    ]
