# Generated by Django 3.2.25 on 2024-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240421_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Enter the publication date in the format YYYY-MM-DD.', null=True),
        ),
    ]
